### ISSUE TITLE
Displaying only 30 results per page

### ISSUE THREAD

**Issue by MasonHolland** [charliecorrigan/bike-share#16]
http://stackoverflow.com/questions/2117320/set-maximum-displayed-rows-count-for-html-table

http://www.easywayserver.com/java/jsp-pagination/

http://stackoverflow.com/questions/3389511/how-to-limit-the-html-table-records-in-each-page

https://www.daniweb.com/programming/web-development/threads/251757/displaying-x-number-of-search-results-per-page

**Comment by yoasyo25** [comment]
We can also look at https://github.com/mislav/will_paginate/wiki
